//MAIN ENTRY POINT, ANY ELEMENTS/CHANGES YOU DO HERE ARE TRANSLATED TO EVERY PAGE (ANY CHILDERN YOU ADD HERE WILL DISPLAY ON EVERY PAGE)
// you can also change meta tags, lang, nav bars, footers (anything that you want to display on all pages)

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
